### ISSUE TITLE
Стандартизация ответов от сервера

### ISSUE THREAD

**Issue by ridicoulous** [kunadevelopers/api-docs#1]
Посмотрим на [рынки](https://github.com/kunadevelopers/api-docs#%D1%80%D1%8B%D0%BD%D0%BA%D0%B8): гет запрос по всем рынкам возвращает массив объектов, по ключам которых можно понять о чем речь:
```
[
  {
    "id": "btcusdt",        # ключ валютной пары
    "base_unit": "btc",     # базовая валюта
    "quote_unit": "usdt",   # валюта котировки
    "base_precision": 6,    # округление базовой валюты
    "quote_precision": 2,   # округление валюты котировки
    "display_precision": 1, # точность для групировки ордеров в ордербуке
    "price_change": -1.89   # изменение цены в % за 24 часа
  }
]
```

А инфа по определенному тикеру приходит без ключей, а просто массивом значений, определить что из них что возможно только ориентируясь на комментарии к каждому значению массива. В чем проблема возвращать обычные объекты с ключами/значениями? Если вдруг поменяется сортировка на бекенде или добавится поле?  Ну серьезно ведь, привязка к индексу массива чревата болью и страданиями при малейших телодвижениях.
То же самое происходит в ордерах (если смотреть активные или исполненные) массив значений, половина из которых `null` и не используется, но их надо иметь в виду при парсинге ответа. А вот при отмене ордера приходит вполне себе нормальный объект со внятным описанием, что да как. 
Ребята, давайте таки делать по общепринятым практикам.

**Comment by ridicoulous** [comment]
Есть кто живой тут?

**Comment by WantbeFree** [comment]
Наше API практически полностью повторяет API Bitfinex. Реализация этих методов сделана по аналогии, чтобы быстрее происходила интеграция сторонних программ с нашим API.

**Comment by ridicoulous** [comment]
Спасибо за ответ.
