### ISSUE TITLE
не работает множественная отмена ордеров

### ISSUE THREAD

**Issue by Smahno** [kunadevelopers/api-docs#10]
Что-то у меня не работает множественная отмена ордеров.
...
const apiPath = '/v3/order/cancel';
const nonce = Date.now();
const body = {
    "order_id": [591737733, 554749044]
};
...
получаю
PS D:\MahInfo\Деньги\Крипта\Трейдинг\Bots> node publicReq
{ messages: [ 'order_id_is_invalid' ] }
PS D:\MahInfo\Деньги\Крипта\Трейдинг\Bots>

Поштучная отмена работает без вопросов

**Comment by ridicoulous** [comment]
см #9

**Comment by Smahno** [comment]
ОК
с учетом этого получилось, спасибо
