### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by Keen83** [kunadevelopers/api-docs#7]
Есть примеры десериализации ответов от сервисов (к примеру wallets) в статически типизированных языках как С#?

**Comment by Keen83** [comment]
Если приходит нормальный JSON объект, то его десериализация происходит одной строчкой. А этот массив придется вручную разбирать. Если посмотреть Interactive Brokers или Exante, там такой чепухи нету и в помине. 
Или вы ориентируетесь на другие криптобиржи, которые были по-быстрому на коленке состряпаны?

**Comment by ridicoulous** [comment]
> Если приходит нормальный JSON объект, то его десериализация происходит одной строчкой. А этот массив придется вручную разбирать. Если посмотреть Interactive Brokers или Exante, там такой чепухи нету и в помине.
> Или вы ориентируетесь на другие криптобиржи, которые были по-быстрому на коленке состряпаны?

Там на все вопросы подобного формата отсылки идут к Bitfinex. Мол, смотрите, мы взяли топ биржу и по ее образу и подобию делаем апи.

**Comment by ridicoulous** [comment]
> Есть примеры десериализации ответов от сервисов (к примеру wallets) в статически типизированных языках как С#?

https://github.com/ridicoulous/Kuna.Net
Welcome to contributing

**Comment by Keen83** [comment]
> > Есть примеры десериализации ответов от сервисов (к примеру wallets) в статически типизированных языках как С#?
> 
> https://github.com/ridicoulous/Kuna.Net
> Welcome to contributing

И получилось у тебя послать ордер через API v3? У меня постоянно ругается, что сигнатура неверная :(

**Comment by ridicoulous** [comment]
@Keen83 https://github.com/kunadevelopers/api-docs
`⚠️ В данный момент API v3 не поддердивает возможность Создать ордер. Используйте API v2.`

**Comment by Keen83** [comment]
> @Keen83 https://github.com/kunadevelopers/api-docs
> `⚠️ В данный момент API v3 не поддердивает возможность Создать ордер. Используйте API v2.`

Неправильно написал. Получилось ли хоть что-то сделать через v3? У меня даже wallet не тянет
